---
# 더 가벼운 Zookeeper
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: smart-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: wurstmeister/zookeeper:latest  # 더 가벼운 이미지
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: smart-be
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    app: zookeeper

---
# 더 가벼운 Kafka
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-service
  namespace: smart-be
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:latest  # 더 가벼운 이미지
          ports:
            - containerPort: 9092
          env:
            # 최소한의 설정
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-service:9092"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_DELETE_TOPIC_ENABLE
              value: "true"

            # 메모리 절약 설정
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx256M -Xms128M"
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "1"
            - name: KAFKA_LOG_SEGMENT_BYTES
              value: "104857600"  # 100MB
            - name: KAFKA_NUM_PARTITIONS
              value: "1"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"

          resources:
            requests:
              memory: "256Mi"  # 더 많은 메모리
              cpu: "100m"      # 더 많은 CPU
            limits:
              memory: "512Mi"
              cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: smart-be
  labels:
    app: kafka
spec:
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
  selector:
    app: kafka