apiVersion: apps/v1
kind: Deployment
metadata:
  name: paintingequipmentmonitoring
  labels:
    app: paintingequipmentmonitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paintingequipmentmonitoring
  template:
    metadata:
      labels:
        app: paintingequipmentmonitoring
    spec:
      containers:
        - name: paintingequipmentmonitoring
          image: "username/paintingequipmentmonitoring:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
